AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - '.idea/**/*'
    - '.git/**/*'
    - '*.lock'
    - 'vendor/**/*'

Layout/AlignParameters:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: false

Metrics/AbcSize:
  Max: 28

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 256

Metrics/MethodLength:
  Max: 128
  CountComments: false

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/EmptyLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false